# h2
spring:
  h2:
    console:
      enabled: true

# h2 DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dev
    username: sa
    password:


# JPA
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
